// import message overrides here

/**
 * Optimal Errors
 * This module contains a list of all the errors we can expect optimal to return to us.
 * These objects should be used to determine the correct course of action to take
 * once the error is returned.
 */

module.exports = {
  '2701': { message: 'None The Equifax validation was accepted with the condition that the customer’s request should be verified.' },
  '5269': { message: 'The ID(s) specified in the URL do not correspond to the values in the system.' },
  '5270': { message: 'The API key provided with the request does not have permission to access the data requested.' },
  '5271': { message: 'You requested a response in an unsupported format.' },
  '5272': { message: 'Your request was submitted in an unsupported format.' },
  '5273': { message: 'Either the URL is invalid or the server is not deployed properly.' },
  '5274': { message: 'The API key specified for this request cannot be used because it has expired or has been disabled/locked.' },
  '5275': { message: 'The API key specified for this request cannot be used because it has expired or has been disabled/locked.' },
  '5276': { message: 'The API key specified for this request cannot be used because it has expired or has been disabled/locked.' },
  '5277': { message: 'The API key specified for this request cannot be used because it has expired or has been disabled/locked.' },
  '5278': { message: 'The API key was not accepted for an unknown reason.' },
  '5279': { message: 'The ID/password for the API key are invalid.' },
  '5502': { message: 'Either the payment token is invalid or the corresponding profile or bank account is not active.' },
  '6001': { message: 'The identification service is disabled.' },
  '6002': { message: 'There is a mismatch between the URL and the question type.' },
  '6004': { message: 'The follow-up question set has already been submitted.' },
  '6005': { message: 'There is an issue with the account configuration.' },
  '6006': { message: 'A communication error occurred.' },
  '6007': { message: 'An error occurred with the external processing gateway.' },
  '6008': { message: 'The external gateway responded with an error.' },
  '6009': { message: 'The user has taken too long to submit the answer and the transaction has timed out.' },
  '7500': { message: 'The profileId included in your request could not be found.' },
  '7501': { message: 'You did not specify a parent merchant legal entity in your request.' },
  '7502': { message: 'The parent merchant legal entity you included in your request could not be identified.' },
  '7503': { message: 'The card number you are trying to add to this profile is already used by this profile.' },
  '7504': { message: 'The card number you are trying to add to this profile is already used by another profile.' },
  '7505': { message: 'The merchantCustomerId provided for this profile has already been used for another profile.' },
  '7511': { message: 'The address ID provided in your request could not be found.' },

  '1000': { action: 'D', message: 'An internal error occurred. Please contact Technical Support before retrying the transaction.' },
  '1003': { action: 'D', message: 'An error occurred with the external processing gateway. Do not retry the transaction. Contact Technical Support for more information.' },
  '1006': { action: 'D', message: 'An error occurred with the external processing gateway. Do not retry the transaction. Contact Technical Support for more information.' },
  '1008': { action: 'D', message: 'An internal error occurred. Do not retry the transaction. Contact Technical Support for more information.' },
  '1018': { action: 'D', message: 'The external processing gateway has reported the transaction is unauthorized. Do not retry the transaction. Contact Technical Support for more information.' },
  '1043': { action: 'D', message: 'The external processing gateway has reported the account type is invalid. Do not retry the transaction. Contact Technical Support for more information.' },
  '1060': { action: 'D', message: 'The external processing gateway has reported a limit has been exceeded. Do not retry the transaction.' },
  '1087': { action: 'D', message: 'The external processing gateway has rejected the transaction. Do not retry the transaction. Contact Technical Support for more information.' },
  '2000': { action: 'D', message: 'The echeck status cannot be found.' },
  '2004': { action: 'D', message: 'The echeck transaction cannot be found.' },
  '2100': { action: 'D', message: 'You have attempted to refund a Charge transaction that is not in a completed state. Do not retry the transaction.' },
  '2445': { action: 'D', message: 'The customer tried to register an EFT bank account that is already used by another customer. Do not retry the transaction.' },
  '2500': { action: 'D', message: 'A suitable merchant account could not be found for this request. Do not retry the transaction. Contact Technical Support for more information.' },
  '2501': { action: 'D', message: 'An internal error occurred. Do not retry the transaction. Contact Technical Support for more information.' },
  '2514': { action: 'D', message: 'An internal error occurred. Your merchant credentials could not be found. Do not retry the transaction. Contact Technical Support for more information.' },
  '2516': { action: 'D', message: 'An internal error occurred. Do not retry the transaction. Please contact Technical Support.' },
  '2517': { action: 'D', message: 'An internal error occurred. Do not retry the transaction. Please contact Technical Support.' },
  '2519': { action: 'D', message: 'You submitted a request for a shop that is disabled. Do not retry the transaction.' },
  '2521': { action: 'D', message: 'An internal error occurred. Your shop is not configured properly. Do not retry the transaction. Contact Technical Support for more information.' },
  '2524': { action: 'D', message: 'An internal error occurred. The customer profile is not configured properly. Do not retry the transaction. Contact Technical Support for more information.' },
  '2530': { action: 'D', message: 'An internal error occurred. Do not retry the transaction. Contact Technical Support for more information.' },
  '2532': { action: 'D', message: 'Your shop is not configured to process any payments. Do not retry the transaction. Contact Technical Support for more information.' },
  '2533': { action: 'D', message: 'Your shop is not configured to process the selected payment method. Do not retry the transaction. Contact Technical Support for more information.' },
  '2536': { action: 'D', message: 'The transaction was declined because the maximum number of attempts has been reached. Do not retry the transaction.' },
  '2537': { action: 'D', message: 'The bank account validation failed because the maximum number of attempts has been reached. Do not retry the transaction.' },
  '2538': { action: 'D', message: 'The customer entered an invalid micro deposit amount.' },
  '2542': { action: 'D', message: 'The customer profile validation failed the AVS check.' },
  '2544': { action: 'D', message: 'The customer profile does not have the credit card information required for validation.' },
  '2546': { action: 'D', message: 'The customer tried to register a credit card that is already used by another customer. Do not retry the transaction.' },
  '2553': { action: 'D', message: 'Our system cannot find the successful enrollment response associated with your shop request ID. Do not retry the transaction. Contact Technical Support for more information.' },
  '2704': { action: 'D', message: 'The Equifax validation was rejected. Do not retry the transaction.' },
  '2709': { action: 'D', message: 'The bank rejected the transaction. It could not process the request.' },
  '2711': { action: 'D', message: 'The validation was rejected for the profile update. Do not retry the transaction.' },
  '3007': { action: 'D', message: 'Your request has failed the AVS check. Note that the amount may have been reserved on the customer’s card and will be released in 3-5 business days. Please ensure the billing address is accurate before retrying the transaction.' },
  '3008': { action: 'D', message: 'You submitted a card type for which the merchant account is not configured.' },
  '3009': { action: 'D', message: 'Your request has been declined by the issuing bank.' },
  '3011': { action: 'D', message: 'Your request has been declined by the issuing bank because the card used is a restricted card. Contact the cardholder’s credit card company for further investigation.' },
  '3012': { action: 'D', message: 'Your request has been declined by the issuing bank because the credit card expiry date submitted is invalid.' },
  '3013': { action: 'D', message: 'Your request has been declined by the issuing bank due to problems with the credit card account.' },
  '3014': { action: 'D', message: 'Your request has been declined – the issuing bank has returned an unknown response. Contact the cardholder’s credit card company for further investigation.' },
  '3015': { action: 'D', message: 'The bank has requested that you process the transaction manually by calling the cardholder’s credit card company.' },
  '3016': { action: 'D', message: 'The bank has requested that you retrieve the card from the cardholder – it may be a lost or stolen card.' },
  '3022': { action: 'D', message: 'The card has been declined due to insufficient funds.' },
  '3023': { action: 'D', message: 'Your request has been declined by the issuing bank due to its proprietary card activity regulations.' },
  '3024': { action: 'D', message: 'Your request has been declined because the issuing bank does not permit the transaction for this card.' },
  '3026': { action: 'D', message: 'The external processing gateway has reported the account type is invalid. Do not retry the transaction. Contact Technical Support for more information.' },
  '3027': { action: 'D', message: 'The external processing gateway has reported a limit has been exceeded. Do not retry the transaction.' },
  '3029': { action: 'D', message: 'The external processing gateway has rejected the transaction. Do not retry the transaction. Contact Technical Support for more information.' },
  '3030': { action: 'D', message: 'The external processing gateway has reported the transaction is unauthorized. Do not retry the transaction. Contact Technical Support for more information.' },
  '3032': { action: 'D', message: 'Your request has been declined by the issuing bank or external gateway because the card is probably in one of their negative databases.' },
  '3035': { action: 'D', message: 'Your request has been declined due to exceeded PIN attempts.' },
  '3036': { action: 'D', message: 'Your request has been declined due to an invalid issuer.' },
  '3037': { action: 'D', message: 'Your request has been declined because it is invalid.' },
  '3038': { action: 'D', message: 'Your request has been declined due to customer cancellation.' },
  '3039': { action: 'D', message: 'Your request has been declined due to an invalid authentication value.' },
  '3040': { action: 'D', message: 'Your request has been declined because the request type is not permitted on the card.' },
  '3041': { action: 'D', message: 'Your request has been declined due to a timeout.' },
  '3042': { action: 'D', message: 'Your request has been declined due to a cryptographic error.' },
  '3044': { action: 'D', message: 'You have submitted a duplicate request.' },
  '3045': { action: 'D', message: 'You submitted an invalid date format for this request.' },
  '3046': { action: 'D', message: 'The transaction was declined because the amount was set to zero.' },
  '3047': { action: 'D', message: 'The transaction was declined because the amount exceeds the floor limit.' },
  '3048': { action: 'D', message: 'The transaction was declined because the amount is less than the floor limit.' },
  '3049': { action: 'D', message: 'The bank has requested that you retrieve the card from the cardholder – the credit card has expired.' },
  '3050': { action: 'D', message: 'The bank has requested that you retrieve the card from the cardholder – fraudulent activity is suspected.' },
  '3051': { action: 'D', message: 'The bank has requested that you retrieve the card from the cardholder – contact the acquirer for more information.' },
  '3052': { action: 'D', message: 'The bank has requested that you retrieve the card from the cardholder – the credit card is restricted.' },
  '3053': { action: 'D', message: 'The bank has requested that you retrieve the card from the cardholder – please call the acquirer.' },
  '3054': { action: 'D', message: 'The transaction was declined due to suspected fraud.' },
  '3202': { action: 'D', message: 'You have exceeded the maximum number of settlements allowed. Contact Technical Support for more information.' },
  '3206': { action: 'D', message: 'The external processing gateway has rejected the transaction. Do not retry the transaction. Contact Technical Support for more information.' },
  '3415': { action: 'D', message: 'You cannot cancel this transaction. It is not in a state that can be cancelled. It may already have been completed and therefore not be in a pending state.' },
  '3502': { action: 'D', message: 'The authorization has already been settled. You cannot process an authorization reversal transaction against an authorization that has been settled.' },
  '3601': { action: 'D', message: 'The 3D Secure authentication of this cardholder by the card issuer failed.' },
  '3604': { action: 'D', message: 'The original authorization or purchase request has expired. The 3D Secure authentication request must be completed within 60 minutes of the original authorization or purchase.' },
  '3605': { action: 'D', message: 'The 3D Secure authentication service was not available for the card used in this transaction.' },
  '3702': { action: 'D', message: 'You cannot cancel this payment transaction. It is not in a state that can be cancelled. It may already have been completed and therefore not be in a pending state.' },
  '3707': { action: 'D', message: 'The transaction referred to is missing responses.' },
  '3800': { action: 'D', message: 'The transaction was declined by the authentication gateway. Do not retry the transaction.' },
  '3801': { action: 'D', message: 'The transaction was declined by the payment gateway. Do not retry the transaction.' },
  '3803': { action: 'D', message: 'The transaction attempt failed. Do not retry the transaction. Please contact Technical Support for more information.' },
  '3806': { action: 'D', message: 'You have attempted a refund, but no amount could be found that was eligible for refund. Do not retry the transaction.' },
  '3807': { action: 'D', message: 'You have attempted a refund, but a simultaneous refund attempt has been detected. Do not retry the transaction.' },
  '3808': { action: 'D', message: 'You have attempted a refund, but the transaction was refused by the payment provider. Do not retry the transaction.' },
  '3809': { action: 'D', message: 'The payment provider for the transaction you attempted denied you permission. Do not retry the transaction.' },
  '3810': { action: 'D', message: 'The payment transaction is pending due to payment provider fraud-management filters. Do not retry the transaction.' },
  '3811': { action: 'D', message: 'The request has been cancelled by the customer.' },
  '3812': { action: 'D', message: 'The cartItem amounts do not equal the totalAmount. Do not retry the transaction.' },
  '4000': { action: 'D', message: 'The transaction was declined by our Risk Management department.' },
  '4001': { action: 'D', message: 'The card number or email address associated with this transaction is in our negative database.' },
  '4002': { action: 'D', message: 'The transaction was declined by our Risk Management department.' },
  '5017': { action: 'D', message: 'The merchant account submitted with your request is not enabled. Do not retry the transaction. Contact Technical Support for more information.' },
  '5019': { action: 'D', message: 'There is no processor set up for the merchant account submitted with your request. Do not retry the transaction. Contact Technical Support for more information.' },
  '5021': { action: 'D', message: 'Your transaction request has been declined. Please verify the transaction details before you attempt this transaction again. Should you require more information, please contact Technical Support.' },
  '5040': { action: 'D', message: 'Your merchant account is not configured for the transaction you attempted. Please contact Technical Support for more information.' },
  '5050': { action: 'D', message: 'An error occurred with your merchant account configuration. Please contact Technical Support.' },
  '7000': { action: 'D', message: 'The address you are trying to create already exists.' },
  '7010': { action: 'D', message: 'The consumer you are trying to create already exists.' },
  '7020': { action: 'D', message: 'The contact method you are trying to create already exists.' },
  '7040': { action: 'D', message: 'The payment method you are trying to create already exists.' },
  '7050': { action: 'D', message: 'The billing schedule you are trying to create already exists.' },
  '7097': { action: 'D', message: 'An internal error occurred. Response Detail could not be generated.' },
  '7090': { action: 'D', message: 'The consumer status you are trying to create already exists.' },
  '8078': { action: 'D', message: 'You have submitted a duplicate request within the last 24 hours.' },
  '8079': { action: 'D', message: 'You have submitted a file that has already been processed within the last 24 hours.' },
  '8081': { action: 'D', message: 'You have submitted an empty file.' },
  '8089': { action: 'D', message: 'You have submitted a file that exceeds the file size limit.' },
  '9000': { action: 'D', message: 'Your transaction request could not be processed because your merchant account has no available child accounts for load balancing.' },
  '9001': { action: 'D', message: 'Your transaction request could not be processed because your merchant account has no available child accounts for tier routing.' },
  '9002': { action: 'D', message: 'Your transaction request could not be processed because your merchant account has no available child accounts for sticky routing.' },
  '9003': { action: 'D', message: 'Your transaction request could not be processed because your merchant account has no available child accounts for bin country routing.' },
  '9004': { action: 'D', message: 'Your transaction request could not be processed because your merchant account has no available child accounts for brand routing.' },
  '9005': { action: 'D', message: 'Your transaction request could not be processed because your merchant account has no available child accounts for keyword routing.' },
  '3028': { action: 'R', message: 'The external processing gateway has reported a system error. Please retry the transaction.' },
  '3802': { action: 'R', message: 'The transaction was not completed successfully. Please retry the transaction.' },
  '8126': { action: 'R', message: 'You have submitted an invalid bank country in your request. Please verify your parameter and retry the transaction.' },
  '1001': { action: 'R', message: 'An error occurred with the external processing gateway. Please retry the transaction.' },
  '1002': { action: 'R', message: 'An internal error occurred. Please retry the transaction.' },
  '1007': { action: 'R', message: 'An internal error occurred. Please retry the transaction.' },
  '1078': { action: 'R', message: 'The external processing gateway has reported a system error. Please retry the transaction.' },
  '2101': { action: 'R', message: 'The requested refund amount exceeds the remaining Charge amount. Please verify your parameters and retry the transaction.' },
  '2102': { action: 'R', message: 'You have submitted an invalid bank country in your request. Please verify your parameter and retry the transaction.' },
  '2511': { action: 'R', message: 'An internal error occurred. Please retry the transaction. Contact Technical Support if the error persists.' },
  '2515': { action: 'R', message: 'An internal error occurred. Please retry the transaction.' },
  '2518': { action: 'R', message: 'An internal error occurred. Please retry the transaction. Contact Technical Support if the error persists.' },
  '2523': { action: 'R', message: 'An internal error occurred. Please retry the transaction. Contact Technical Support if the error persists.' },
  '2526': { action: 'R', message: 'An internal profile management error occurred and your request could not be processed. Please retry the transaction. Contact Technical Support if the error persists.' },
  '2529': { action: 'R', message: 'An internal error occurred. Please retry the transaction.' },
  '2539': { action: 'R', message: 'An internal error occurred. Please retry the transaction. Contact Technical Support if the error persists.' },
  '2541': { action: 'R', message: 'An internal error occurred when sending the micro deposit transaction. Please retry the transaction. Contact Technical Support if the error persists.' },
  '2702': { action: 'R', message: 'An internal error has occurred while processing an Equifax transaction. Retry the transaction. Contact Technical Support if the error persists.' },
  '2703': { action: 'R', message: 'Some or all of the Equifax databases are down. Retry the transaction. Contact Technical Support if the error persists.' },
  '2705': { action: 'R', message: 'The Equifax validation was rejected and should be treated manually. The merchant can contact the customer directly.' },
  '2706': { action: 'R', message: 'The Equifax validation was rejected due to invalid input. Please verify your parameters and retry the transaction.' },
  '2707': { action: 'R', message: 'The Equifax validation was rejected due to an invalid address. Please verify your parameters and retry the transaction.' },
  '2708': { action: 'R', message: 'An internal error occurred. The Equifax response codes are missing. Please verify your parameters and retry the transaction.' },
  '3018': { action: 'R', message: 'The bank has requested that you retry the transaction.' },
  '3020': { action: 'R', message: 'The bank has requested that you retry the transaction.' },
  '3025': { action: 'R', message: 'The external processing gateway has reported invalid data. Please verify your parameters and retry the transaction.' },
  '5051': { action: 'C', message: 'You have submitted an invalid confirmation number. Please verify your parameter and retry.' },
  '5052': { action: 'C', message: 'You have submitted an invalid Zip/Postal code. Please verify your parameter and retry the transaction.' },
  '5053': { action: 'C', message: 'You have submitted invalid personal ID information. Please verify your parameters and retry the transaction.' },
  '2001': { action: 'C', message: 'You submitted a request containing a bank account, amount, and check number already used together in a request within the last 24 hours.' },
  '2006': { action: 'C', message: 'You have submitted a Decline transaction in response to a Settlement attempt.' },
  '2008': { action: 'C', message: 'You have submitted an invalid routing number. Please verify your parameter and retry the transaction.' },
  '2009': { action: 'C', message: 'You have submitted an invalid bank account number. Please verify your parameter and retry the transaction.' },
  '2010': { action: 'C', message: 'You have submitted an invalid check number. Please verify your parameter and retry the transaction.' },
  '3001': { action: 'C', message: 'You submitted an unsupported card type with your request. Please verify this parameter and retry the transaction.' },
  '3002': { action: 'C', message: 'You submitted an invalid card number or brand or combination of card number and brand with your request. Please verify these parameters and retry the transaction.' },
  '3003': { action: 'C', message: 'You submitted an incorrect value for the cvdIndicator parameter with your request. Please verify this parameter and retry the transaction.' },
  '3004': { action: 'C', message: 'You have requested an AVS check. Please ensure that the zip/postal code is provided.' },
  '3005': { action: 'C', message: 'You submitted an incorrect value for the cvd parameter with your request. Please verify this parameter and retry the transaction.' },
  '3006': { action: 'C', message: 'You submitted an expired credit card number with your request. Please verify this parameter and retry the request.' },
  '3017': { action: 'C', message: 'You submitted an invalid credit card number with your request. Please verify this parameter and retry the transaction.' },
  '3019': { action: 'C', message: 'Your request has failed the CVD check. Please note that the amount may still have been reserved on the customer’s card, in which case it will be released in from 3 to 5 business days. Please ensure the CVD value is accurate before retrying the transaction.' },
  '3703': { action: 'C', message: 'The external gateway has reported that you have submitted an invalid amount with your request. Please verify this parameter and retry the transaction.' },
  '5003': { action: 'C', message: 'You submitted an invalid amount with your request. Please verify this parameter and retry the transaction.' },
  '5032': { action: 'C', message: 'You submitted an invalid city with your request. Please verify this parameter and retry the transaction.' },
  '5033': { action: 'C', message: 'You submitted an invalid country with your request. Please verify this parameter and retry the transaction.' },
  '5034': { action: 'C', message: 'You submitted an invalid email address with your request. Please verify this parameter and retry the transaction.' },
  '5035': { action: 'C', message: 'You submitted an invalid name with your request. Please verify this parameter and retry the transaction.' },
  '5036': { action: 'C', message: 'You submitted an invalid phone number with your request. Please verify this parameter and retry the transaction.' },
  '5037': { action: 'C', message: 'You submitted an invalid zip/postal code with your request. Please verify this parameter and retry the transaction.' },
  '5038': { action: 'C', message: 'You submitted an invalid state/province with your request. Please verify this parameter and retry the transaction.' },
  '5039': { action: 'C', message: 'You submitted an invalid street with your request. Please verify this parameter and retry the transaction.' },
  '1004': { action: 'M', message: 'Your account is not enabled for this transaction type. Please verify your parameters and retry the transaction.' },
  '1028': { action: 'M', message: 'The external processing gateway has reported invalid data. Please verify your parameters and retry the transaction.' },
  '1101': { action: 'M', message: 'You submitted an unsupported card/currency combination with your request.' },
  '2002': { action: 'M', message: 'The echeck request cannot be found. Please verify your parameters and retry.' },
  '2003': { action: 'M', message: 'The payment type you provided conflicts with the bank account type you provided. Please verify your parameters and retry the transaction.' },
  '2005': { action: 'M', message: 'An internal error occurred. Please verify your parameters and retry the transaction.' },
  '2007': { action: 'M', message: 'The payment type included with your request cannot be used in Credit transaction mode. Please verify your parameters and retry the request.' },
  '2011': { action: 'M', message: 'You have submitted a mandate reference that does not exist. Please verify your parameter and retry the transaction.' },
  '2012': { action: 'M', message: 'You have submitted a mandate reference that is not active yet. Please resubmit your request after the mandate becomes active or resubmit your request including the txnDate element with a date after: <date>' },
  '2013': { action: 'M', message: 'You have submitted an invalid mandate reference. Please verify your parameter and retry the transaction.' },
  '2014': { action: 'M', message: 'The mandate reference is already in use for the specified bank account information. Please specify a different mandate reference.' },
  '2016': { action: 'M', message: 'The paymentToken element cannot be used together with the check element or the billingDetails element.' },
  '2017': { action: 'M', message: 'The payment token bank scheme does not match the merchant account bank scheme.' },
  '2502': { action: 'M', message: 'The authentication failed for your transaction request. Either your credentials were entered incorrectly or your request was tampered with. Please verify your request and retry the transaction.' },
  '2503': { action: 'M', message: 'You submitted an invalid shop ID. It must be a numeric value.' },
  '2504': { action: 'M', message: 'You submitted a shop ID for which a shop does not exist. Please verify your parameters and retry the transaction.' },
  '2505': { action: 'M', message: 'No merchant account could be found for the currency you submitted. Please verify your parameters and retry the transaction.' },
  '2506': { action: 'M', message: 'More than one merchant account was found for the currency you submitted. Please provide a merchant account number and retry the request.' },
  '2507': { action: 'M', message: 'The merchant account submitted does not correspond to the shop ID you submitted. Please verify your parameters and retry the transaction.' },
  '2508': { action: 'M', message: 'You submitted a request that is missing the encodedMessage parameter. Please verify your parameters and retry the transaction.' },
  '2509': { action: 'M', message: 'You submitted a request that has an invalid encodedMessage parameter. The encodedMessage could not be Base64 decoded. Please verify your parameters and retry the request.' },
  '2510': { action: 'M', message: 'You submitted an invalid XML request. Please verify your request and retry the transaction.' },
  '2512': { action: 'M', message: 'You submitted a request that is missing the signature parameter. Please verify your parameters and retry the transaction.' },
  '2513': { action: 'M', message: 'You submitted a request that is missing the Shop ID parameter. Please verify your parameters and retry the transaction.' },
  '2520': { action: 'M', message: 'The cartItem and feeItem amounts do not equal the totalAmount. Please verify your parameters and retry the transaction.' },
  '2525': { action: 'M', message: 'The customer profile associated with the token provided could not be located. Please verify your parameters and retry the transaction.' },
  '2527': { action: 'M', message: 'You submitted a request with an unsupported locale. Please verify your parameters and retry the transaction.' },
  '2528': { action: 'M', message: 'You submitted a request with a merchant customer ID that is not associated with the customer token provided. Please verify your parameters and retry the transaction.' },
  '2531': { action: 'M', message: 'A customer profile with the same merchant customer ID already exists. Please verify your parameters and retry the transaction.' },
  '2534': { action: 'M', message: 'The customer profile associated with the token you provided is not active. Please verify your parameters and ensure the customer status is active and then retry the transaction.' },
  '2535': { action: 'M', message: 'The customer profile associated with the token you provided has a bank account that is not validated. Please verify your parameters or have your customer validate their account and then retry the transaction.' },
  '2540': { action: 'M', message: 'The merchant reference number already exists. Please verify your parameters and retry the transaction.' },
  '2543': { action: 'M', message: 'The customer has a status that cannot be validated. Please reset the customer status before retrying the transaction.' },
  '2547': { action: 'M', message: 'The customer profile associated with the token you provided does not have a credit card. Please verify your parameters, and retry the transaction.' },
  '2548': { action: 'M', message: 'The customer profile used for this transaction has not been created. Please verify your parameters and retry the transaction.' },
  '2549': { action: 'M', message: 'Your shop is not configured to register a bank account for the country you submitted. Please verify your parameters and retry the transaction.' },
  '2550': { action: 'M', message: 'The customer profile associated with the token you provided does not have a registered bank account. Please verify your parameters and retry the transaction.' },
  '2551': { action: 'M', message: 'You submitted a request that contains an invalid payment method. Please verify your parameters and retry the transaction.' },
  '2552': { action: 'M', message: 'You submitted a request that contains an invalid shop request ID. Please verify your parameters and retry the transaction.' },
  '2554': { action: 'M', message: 'The customer profile associated with the token you provided is disabled. Please verify your parameters and ensure the customer status is active, and retry the transaction.' },
  '2555': { action: 'M', message: 'The payment token is not associated with the customer profile you provided. Please verify your parameters and retry the transaction.' },
  '2556': { action: 'M', message: 'The credit card selected for this transaction is not active. Please verify your parameters and retry the transaction.' },
  '2557': { action: 'M', message: 'The confirmation number included in this request could not be found. Please verify this parameter and retry the transaction.' },
  '2558': { action: 'M', message: 'The transaction cannot be cancelled. Please verify your parameters and ensure you are attempting to cancel the correct transaction. If the error persists, contact Technical Support.' },
  '2710': { action: 'M', message: 'No email template is set up, so no email could be sent to confirm the transaction.' },
  '3021': { action: 'M', message: 'The confirmation number included in this request could not be found. Please verify this parameter and retry the transaction.' },
  '3031': { action: 'M', message: 'The confirmation number you submitted with your request references a transaction that is not on hold. Please verify this parameter and retry the transaction.' },
  '3200': { action: 'M', message: 'You have submitted an invalidly formatted authorization ID for this settlement. Please verify this parameter and retry the transaction.' },
  '3201': { action: 'M', message: 'The authorization ID included in this settlement request could not be found. Please verify this parameter and retry the transaction.' },
  '3203': { action: 'M', message: 'The authorization is either fully settled or cancelled.' },
  '3204': { action: 'M', message: 'The requested settlement amount exceeds the remaining authorization amount.' },
  '3205': { action: 'M', message: 'The authorization you are attempting to settle has expired.' },
  '3402': { action: 'M', message: 'The requested credit amount exceeds the remaining settlement amount.' },
  '3403': { action: 'M', message: 'You have already processed the maximum number of credits allowed for this settlement.' },
  '3404': { action: 'M', message: 'The settlement has already been fully credited.' },
  '3405': { action: 'M', message: 'The settlement you are attempting to credit has expired.' },
  '3406': { action: 'M', message: 'The settlement you are attempting to credit has not been batched yet. There are no settled funds available to credit.' },
  '3407': { action: 'M', message: 'The settlement referred to by the transaction response ID you provided cannot be found. Please verify this parameter and retry the transaction.' },
  '3408': { action: 'M', message: 'You have submitted an invalidly formatted response ID for the original purchase or settlement. Please verify this parameter and retry the transaction.' },
  '3409': { action: 'M', message: 'The authorization ID included in this credit request could not be found. Please verify this parameter and retry the transaction.' },
  '3410': { action: 'M', message: 'The refund request failed.' },
  '3411': { action: 'M', message: 'The cancel refund request failed.' },
  '3412': { action: 'M', message: 'The Credit transaction you attempted was not permitted because your merchant account is in overdraft.' },
  '3413': { action: 'M', message: 'The requested Credit amount exceeds the permissible Visa credit ratio. Please verify this parameter and retry the transaction.' },
  '3414': { action: 'M', message: 'The credit referred to by the transaction response ID you provided cannot be found. Please verify this parameter and retry the transaction.' },
  '3416': { action: 'M', message: 'The external processing gateway for which your merchant account is configured does not support partial settlements. Ensure that the amount you are trying to settle is identical to the amount in the original authorization and retry the transaction.' },
  '3417': { action: 'M', message: 'There is already another request being processed on the transaction referenced for this request. Please use the confirmation number used for this request to run a report or lookup to determine the results.' },
  '3418': { action: 'M', message: 'The external processing gateway for which your merchant account is configured does not support partial credits.' },
  '3500': { action: 'M', message: 'The confirmation number included in this request could not be found. Please verify this parameter and retry the transaction.' },
  '3501': { action: 'M', message: 'The requested authorization reversal amount exceeds the remaining authorization amount.' },
  '3503': { action: 'M', message: 'The authorization reversal transaction is not supported for the card type used for the authorization you are attempting to reverse.' },
  '3504': { action: 'M', message: 'The external processing gateway for which your merchant account is configured does not support partial authorization reversals. Ensure that the amount you are trying to reverse is identical to the amount in the original authorization and retry the transaction.' },
  '3505': { action: 'M', message: 'The authorization reversal could not be completed.' },
  '3506': { action: 'M', message: 'The reversal amount exceeds the remaining amount of the authorization.' },
  '3602': { action: 'M', message: 'The confirmation number included in the 3D Secure authentication request could not be found. The confirmation number must be the one returned by the payment processor in response to the original authorization or purchase.' },
  '3603': { action: 'M', message: 'You submitted a request that is not available for 3D Secure authentication.' },
  '3701': { action: 'M', message: 'The confirmation number included in this request could not be found. Please verify this parameter and retry the transaction.' },
  '3704': { action: 'M', message: 'The transaction referred to cannot be found.' },
  '3705': { action: 'M', message: 'The transaction referred to uses a different card number.' },
  '3706': { action: 'M', message: 'The transaction referred to is not fully authenticated.' },
  '3708': { action: 'M', message: 'The transaction referred to has not been settled.' },
  '3804': { action: 'M', message: 'You have attempted to refund a payment transaction that is not in a completed state. Do not retry the transaction.' },
  '3805': { action: 'M', message: 'The attempted refund amount exceeds the amount that remains available for refund. Please verify this parameter and retry the transaction.' },
  '3850': { action: 'M', message: 'The prepaid card associated with the payment token is no longer valid. Please prompt the customer to enter new card details.' },
  '5000': { action: 'M', message: 'Your merchant account authentication failed. Either your store ID/password are invalid or the IP address from which you are sending the transaction has not been authorized. Please verify these parameters and retry the transaction. Please contact Technical Support if the error persists.' },
  '5001': { action: 'M', message: 'You submitted an invalid currency code with your request. Please verify this parameter and retry the transaction.' },
  '5002': { action: 'M', message: 'You submitted an invalid payment method with your request. Please verify this parameter and retry the transaction.' },
  '5004': { action: 'M', message: 'You submitted an invalid account type with your request. Please verify this parameter and retry the transaction.' },
  '5005': { action: 'M', message: 'You submitted an invalid operation type with your request. Please verify this parameter and retry the transaction.' },
  '5006': { action: 'M', message: 'You submitted an invalid personal ID type with your request. Please verify this parameter and retry the transaction.' },
  '5007': { action: 'M', message: 'You submitted an invalid product type with your request. Please verify this parameter and retry the transaction.' },
  '5008': { action: 'M', message: 'You submitted an invalid carrier with your request. Please verify this parameter and retry the transaction.' },
  '5009': { action: 'M', message: 'You submitted an invalid ship method with your request. Please verify this parameter and retry the transaction.' },
  '5010': { action: 'M', message: 'You submitted an invalid ID country with your request. Please verify this parameter and retry the transaction.' },
  '5011': { action: 'M', message: 'You submitted an invalid order date and time with your request. Please verify this parameter and retry the transaction.' },
  '5012': { action: 'M', message: 'You submitted an invalid ship country parameter with your request. Please verify this parameter and retry the transaction.' },
  '5013': { action: 'M', message: 'You submitted an invalid ship state parameter with your request. Please verify this parameter and retry the transaction.' },
  '5014': { action: 'M', message: 'You submitted an invalid transaction type with your request. Please verify this parameter and retry the transaction.' },
  '5015': { action: 'M', message: 'At least one of the parameters in your request exceeds the maximum number of characters allowed. Please verify your parameters and retry the transaction.' },
  '5016': { action: 'M', message: 'Either you submitted an invalid merchant account or the merchant account could not be found. Please verify this parameter and retry the transaction. Please contact Technical Support if the error persists.' },
  '5018': { action: 'M', message: 'You submitted a request that either is missing a field or contains an invalid field.' },
  '5020': { action: 'M', message: 'The currency type included with your request does not match the currency type of your merchant account. Please verify your parameters and retry the request.' },
  '5022': { action: 'M', message: 'You submitted a request that is missing search criteria. Please verify your parameters and retry the transaction.' },
  '5023': { action: 'M', message: 'The request is unparsable.' },
  '5024': { action: 'M', message: 'You submitted an invalid ID expiry date for this request. Please verify this parameter and retry the transaction.' },
  '5025': { action: 'M', message: 'The search criteria you submitted is currently not supported. Please verify your search criteria and retry.' },
  '5026': { action: 'M', message: 'The Web Services API does not currently support credit card transactions. Please verify your parameters and retry your transaction.' },
  '5027': { action: 'M', message: 'You submitted an invalid risk service name with your transaction request. Please verify your parameters and retry your transaction.' },
  '5028': { action: 'M', message: 'You submitted a batch file with the same file name, file size, and number of entries within the last 24 hours.' },
  '5029': { action: 'M', message: 'You submitted an improperly formatted batch file.' },
  '5030': { action: 'M', message: 'You submitted a batch file that has exceeded the maximum number of rows allowed.' },
  '5031': { action: 'M', message: 'The transaction you have submitted has already been processed.' },
  '5041': { action: 'M', message: 'You submitted an invalid merchantData parameter. Please verify this parameter and retry the transaction.' },
  '5042': { action: 'M', message: 'The merchant reference number is missing or invalid or it exceeds the maximum permissible length. Please verify this parameter and retry the transaction.' },
  '5043': { action: 'M', message: 'You submitted an invalid account open date with your request. Please verify this parameter and retry the transaction.' },
  '5044': { action: 'M', message: 'You submitted an invalid customer ID with your request. Please verify this parameter and retry the transaction.' },
  '5045': { action: 'M', message: 'You submitted an invalid customer IP address with your request. Please verify this parameter and retry the transaction.' },
  '5046': { action: 'M', message: 'You submitted an invalid merchant SIC code with your request. Please verify this parameter and retry the transaction.' },
  '5047': { action: 'M', message: 'You submitted an invalid value for the previous customer parameter with your request. Please verify this parameter and retry the transaction.' },
  '5048': { action: 'M', message: 'You submitted an invalid product code with your request. Please verify this parameter and retry the transaction.' },
  '5049': { action: 'M', message: 'You submitted an invalid value for user data with your request. Please verify this parameter and retry the transaction.' },
  '5054': { action: 'M', message: 'You cannot submit recurring billing elements with this operation type. Please verify that your request includes the correct operation type and retry the transaction.' },
  '5055': { action: 'M', message: 'You submitted an invalid ECI value. Please verify this parameter and retry the transaction.' },
  '5056': { action: 'M', message: 'An ECI value must be provided for 3D Secure authentication. Please verify this parameter and retry the transaction.' },
  '5057': { action: 'M', message: 'You submitted a credit card brand that does not support 3D Secure authentication. Please verify this parameter and retry the transaction.' },
  '5058': { action: 'M', message: 'A CAVV value must be provided for 3D Secure authentication. Please verify this parameter and retry the transaction.' },
  '5059': { action: 'M', message: 'You submitted an invalid value for the currency request service.' },
  '5060': { action: 'M', message: 'You submitted an invalid recurringIndicator parameter with your request. Please verify this parameter and retry the transaction.' },
  '5061': { action: 'M', message: 'A security check failed while processing this transaction. Please retry the transaction. If the error persists, contact Technical Support.' },
  '5062': { action: 'M', message: 'You have submitted invalid characters as part of your request. Please verify that all parameters contain only characters that can be URL encoded, and retry the transaction.' },
  '5063': { action: 'M', message: 'You have submitted an invalid KEYWORD with your request. Please verify this parameter and retry the transaction."' },
  '5065': { action: 'M', message: 'You have requested an invalid status change transition.' },
  '5066': { action: 'M', message: 'The external processing gateway for which your merchant account is configured does not support Independent Credits.' },
  '5067': { action: 'M', message: 'The external processing gateway for which your merchant account is configured does not support Credit Card Payments.' },
  '5068': { action: 'M', message: 'Either you submitted a request that is missing a mandatory field or the value of a field does not match the format expected.' },
  '5069': { action: 'M', message: 'You submitted an invalid TAXPAYER_NAME with your request. Please verify this parameter and retry the transaction.' },
  '5070': { action: 'M', message: 'You submitted an invalid REMITTANCE_TYPE with your request. Please verify this parameter and retry the transaction.' },
  '5071': { action: 'M', message: 'You submitted a request that has invalid search parameters. Please verify your parameters and retry the transaction.' },
  '5072': { action: 'M', message: 'You submitted an invalid REMITTANCE_REFERENCE_NUMBER with your request. Please verify this parameter and retry the transaction.' },
  '5073': { action: 'M', message: 'You submitted an invalid REMITTANCE_PERIOD_END_DATE with your request. Please verify this parameter and retry the transaction.' },
  '5074': { action: 'M', message: 'At least one of the parameters in your request is shorter than the minimum number of characters required. Please verify your parameters and retry the transaction.' },
  '5075': { action: 'M', message: 'At least one of the parameters in your request contains leading/trailing spaces. Please verify your parameters and retry the transaction.' },
  '7001': { action: 'M', message: 'Unable to create address. Try again or contact Technical Support.' },
  '7002': { action: 'M', message: 'Unable to update address. Try again or contact Technical Support.' },
  '7003': { action: 'M', message: 'Unable to locate the specified address.' },
  '7004': { action: 'M', message: 'Unable to load address. Try again or contact Technical Support.' },
  '7005': { action: 'M', message: 'You have provided an invalid address type.' },
  '7006': { action: 'M', message: 'Unable to locate addresses for consumer.' },
  '7007': { action: 'M', message: 'Unable to load addresses. Try again or contact Technical Support.' },
  '7011': { action: 'M', message: 'Unable to create consumer. Try again or contact Technical Support.' },
  '7012': { action: 'M', message: 'Unable to update consumer. Try again or contact Technical Support.' },
  '7013': { action: 'M', message: 'Unable to locate the specified consumer.' },
  '7014': { action: 'M', message: 'Unable to load consumer. Try again or contact Technical Support.' },
  '7015': { action: 'M', message: 'You have specified an invalid consumer creation type.' },
  '7016': { action: 'M', message: 'You have specified an invalid consumer title.' },
  '7021': { action: 'M', message: 'Unable to create contact method. Try again or contact Technical Support.' },
  '7022': { action: 'M', message: 'Unable to update contact method. Try again or contact Technical Support.' },
  '7023': { action: 'M', message: 'Unable to locate the specified contact method.' },
  '7024': { action: 'M', message: 'Unable to load contact method. Try again or contact Technical Support.' },
  '7025': { action: 'M', message: 'You have provided an invalid contact method type.' },
  '7026': { action: 'M', message: 'Unable to locate contact methods for consumer.' },
  '7027': { action: 'M', message: 'Unable to load contact methods. Try again or contact Technical Support.' },
  '7041': { action: 'M', message: 'Unable to create payment method. Try again or contact Technical Support.' },
  '7042': { action: 'M', message: 'Unable to update payment method. Try again or contact Technical Support.' },
  '7043': { action: 'M', message: 'Unable to locate the specified payment method.' },
  '7044': { action: 'M', message: 'Unable to load payment method. Try again or contact Technical Support.' },
  '7045': { action: 'M', message: 'You have provided an invalid payment method type.' },
  '7046': { action: 'M', message: 'Unable to locate payment methods for consumer.' },
  '7047': { action: 'M', message: 'Unable to load payment methods. Try again or contact Technical Support.' },
  '7051': { action: 'M', message: 'Unable to create billing schedule. Try again or contact Technical Support.' },
  '7052': { action: 'M', message: 'Unable to update billing schedule. Try again or contact Technical Support.' },
  '7053': { action: 'M', message: 'Unable to locate the specified billing schedule.' },
  '7054': { action: 'M', message: 'Unable to load billing schedule. Try again or contact Technical Support.' },
  '7055': { action: 'M', message: 'You have provided an invalid payment interval type.' },
  '7056': { action: 'M', message: 'Unable to locate billing schedules for consumer.' },
  '7057': { action: 'M', message: 'Unable to load billing schedules. Try again or contact Technical Support.' },
  '7058': { action: 'M', message: 'Billing amount must be greater than zero.' },
  '7059': { action: 'M', message: 'Unable to update billing schedule status. Try again or contact Technical Support.' },
  '7070': { action: 'M', message: 'Unable to execute the search operation. Try again or contact Technical Support.' },
  '7080': { action: 'M', message: 'Unable to update records. Try again or contact Technical Support.' },
  '7091': { action: 'M', message: 'Unable to create consumer status. Try again or contact Technical Support.' },
  '7092': { action: 'M', message: 'Unable to update consumer status. Try again or contact Technical Support.' },
  '7093': { action: 'M', message: 'Unable to locate the specified consumer status.' },
  '7094': { action: 'M', message: 'Unable to load consumer status. Try again or contact Technical Support.' },
  '7095': { action: 'M', message: 'Unable to locate the merchant legal entity.' },
  '7096': { action: 'M', message: 'Unable to retrieve merchant legal entity. Try again or contact Technical Support.' },
  '7098': { action: 'M', message: 'You have provided an invalid credit card number.' },
  '7100': { action: 'M', message: 'The ddstatus you are trying to create for the paymentMethod already exists.' },
  '7101': { action: 'M', message: 'Unable to create the ddstatus for the paymentMethod. Try again or contact Technical Support.' },
  '7102': { action: 'M', message: 'Unable to update the ddstatus for the paymentMethod. Try again or contact Technical Support.' },
  '7103': { action: 'M', message: 'Unable to locate the specified ddstatus for the paymentMethod.' },
  '7104': { action: 'M', message: 'Unable to load the ddstatus for the paymentMethod. Try again or contact Technical Support.' },
  '7107': { action: 'M', message: 'The customer profile was successfully created but we were unable to load the email template.' },
  '7108': { action: 'M', message: 'The ccstatus you are trying to create for the paymentMethod already exists.' },
  '7109': { action: 'M', message: 'Unable to create the ccstatus for the paymentMethod. Try again or contact Technical Support.' },
  '7110': { action: 'M', message: 'Unable to update the ccstatus for the paymentMethod. Try again or contact Technical Support.' },
  '7111': { action: 'M', message: 'Unable to load the ccstatus for the paymentMethod. Try again or contact Technical Support.' },
  '8000': { action: 'M', message: 'Unable to perform operation. Try again or contact Technical Support.' },
  '8001': { action: 'M', message: 'You have submitted an invalid request. Please verify your parameters and retry.' },
  '8002': { action: 'M', message: 'Your request is missing the consumerInfo element.' },
  '8003': { action: 'M', message: 'Your request is missing a value for the firstName element.' },
  '8004': { action: 'M', message: 'Your request is missing a value for the lastName element.' },
  '8005': { action: 'M', message: 'Your request is missing the billingAddress/shippingAddress element.' },
  '8006': { action: 'M', message: 'Your request is missing billingAddress/shippingAddress information. There is no value for the street element.' },
  '8007': { action: 'M', message: 'Your request is missing billingAddress/shippingAddress information. There is no value for the city element.' },
  '8008': { action: 'M', message: 'Your request is missing billingAddress/shippingAddress information. There is no value for the zip element.' },
  '8009': { action: 'M', message: 'Your request is missing billingAddress/shippingAddress information. There is no value for the country element.' },
  '8010': { action: 'M', message: 'Your request is missing billingAddress/shippingAddress information. There is no value for the state or region element.' },
  '8011': { action: 'M', message: 'Your request is missing the contactMethod element.' },
  '8012': { action: 'M', message: 'Your request is missing a home telephone number or a cell phone number or an email address for the type element.' },
  '8013': { action: 'M', message: 'Your request is missing the paymentMethod element.' },
  '8014': { action: 'M', message: 'Your request is missing a value for the id child element of the billingAddress element.' },
  '8015': { action: 'M', message: 'Your request is missing either the card or check child element of the paymentMethod element.' },
  '8016': { action: 'M', message: 'Your request is missing the card element.' },
  '8017': { action: 'M', message: 'Your request is missing a value for the cardNum element.' },
  '8018': { action: 'M', message: 'Your request is missing a value for the cardType element.' },
  '8019': { action: 'M', message: 'Your request is missing the cardExpiry element.' },
  '8020': { action: 'M', message: 'Your request is missing a value for the month element.' },
  '8021': { action: 'M', message: 'Your request is missing a value for the year element.' },
  '8022': { action: 'M', message: 'Your request is missing the check element.' },
  '8023': { action: 'M', message: 'Your request is missing a value for the accountNum element.' },
  '8024': { action: 'M', message: 'Your request is missing a value for the accountType element.' },
  '8025': { action: 'M', message: 'Your request is missing a value for the routingNum element.' },
  '8026': { action: 'M', message: 'Your request is missing a value for the bankName element.' },
  '8027': { action: 'M', message: 'Your request is missing a value for the checkNum element.' },
  '8028': { action: 'M', message: 'Your request is missing the billingSchedule element.' },
  '8029': { action: 'M', message: 'Your request is missing a value for the intervalCode element.' },
  '8030': { action: 'M', message: 'Your request is missing a value for the nextBillingDate element.' },
  '8031': { action: 'M', message: 'Your request is missing a value for the startDate element.' },
  '8032': { action: 'M', message: 'Your request is missing a value for the amount element.' },
  '8033': { action: 'M', message: 'Your request is missing the merchantAccount element.' },
  '8034': { action: 'M', message: 'Your request is missing a value for the accountNum element.' },
  '8035': { action: 'M', message: 'Your request is missing a value for the storeID element.' },
  '8036': { action: 'M', message: 'Your request is missing a value for the storePwd element.' },
  '8037': { action: 'M', message: 'The credentials supplied with the merchantAccount element could not be validated.' },
  '8038': { action: 'M', message: 'An internal error occurred. Please retry the request.' },
  '8039': { action: 'M', message: 'Your request is missing a value for the consumerId element.' },
  '8040': { action: 'M', message: 'Your request is missing a value for the title element.' },
  '8041': { action: 'M', message: 'Your request is missing a value for the merchantRefNum child element of the consumerInfo element.' },
  '8042': { action: 'M', message: 'Your request is missing a value for the street2 element.' },
  '8043': { action: 'M', message: 'You have submitted an invalid address id element. It does not match the consumerId submitted with the request.' },
  '8044': { action: 'M', message: 'You have submitted an invalid contactMethod id element. It does not match the consumerId submitted with the request.' },
  '8045': { action: 'M', message: 'Your request is missing a value for the paymentMethodId element.' },
  '8046': { action: 'M', message: 'Your request is missing a value for the ccHolderName element.' },
  '8047': { action: 'M', message: 'Your request is missing a value for the merchantRefNum child element of the paymentMethod element.' },
  '8048': { action: 'M', message: 'Your request is missing a value for the id child element of the billingSchedule element.' },
  '8049': { action: 'M', message: 'Your request is missing a value for the serviceName element.' },
  '8050': { action: 'M', message: 'Your request is missing a value for the statusCode element.' },
  '8051': { action: 'M', message: 'Your request is missing a value for the lastDayOfTheMonth element.' },
  '8052': { action: 'M', message: 'Your request is missing a value for the merchantRefNum child element of the billingSchedule element.' },
  '8053': { action: 'M', message: 'Your request contains two consumerId elements that don’t match.' },
  '8054': { action: 'M', message: 'You attempted an unsupported operation.' },
  '8055': { action: 'M', message: 'You have submitted an invalid endDate element.' },
  '8056': { action: 'M', message: 'You have submitted an invalid issueNumber element.' },
  '8057': { action: 'M', message: 'You have submitted an invalid statusCode element.' },
  '8058': { action: 'M', message: 'You have submitted an invalid intervalCode element.' },
  '8059': { action: 'M', message: 'You have submitted an invalid title element.' },
  '8060': { action: 'M', message: 'You have submitted an invalid cardType element.' },
  '8061': { action: 'M', message: 'You have submitted an invalid accountType element.' },
  '8062': { action: 'M', message: 'You have submitted an invalid state element.' },
  '8063': { action: 'M', message: 'You have submitted an invalid country element.' },
  '8064': { action: 'M', message: 'You have submitted an invalid startDate element.' },
  '8065': { action: 'M', message: 'You have submitted an invalid endDate element.' },
  '8066': { action: 'M', message: 'You have submitted an invalid nextBillingDate element.' },
  '8067': { action: 'M', message: 'The endDate cannot be before the startDate.' },
  '8068': { action: 'M', message: 'The nextBillingDate cannot be after the endDate.' },
  '8069': { action: 'M', message: 'The nextBillingDate cannot be before the startDate.' },
  '8070': { action: 'M', message: 'You have submitted an invalid cardExpiry element.' },
  '8071': { action: 'M', message: 'You have submitted an invalid paymentMethod billingAddressId. Either it does not match the consumerId submitted with the request or it is the wrong address type.' },
  '8072': { action: 'M', message: 'You have submitted an invalid paymentMethod shippingAddressId. Either it does not match the consumerId submitted with the request or it is the wrong address type.' },
  '8073': { action: 'M', message: 'You have submitted an invalid contactMethod type element.' },
  '8074': { action: 'M', message: 'You have submitted an invalid paymentMethod id element. It does not match the consumerId submitted with the request.' },
  '8075': { action: 'M', message: 'You have submitted an invalid billingSchedule id element. It does not match the consumerId submitted with the request.' },
  '8076': { action: 'M', message: 'You have submitted an invalid consumerId element. The consumer specified is not registered with this merchant.' },
  '8077': { action: 'M', message: 'You have submitted an invalid billingSchedule paymentMethodId element. The payment method identified is not registered with this consumer.' },
  '8080': { action: 'M', message: 'You have submitted an invalid record type. It is missing the recurringBillingDetails element.' },
  '8082': { action: 'M', message: 'You have submitted an invalid request.' },
  '8083': { action: 'M', message: 'Your request is missing a value for the cvv element.' },
  '8084': { action: 'M', message: 'You have submitted an invalid cvv element.' },
  '8085': { action: 'M', message: 'Your request is missing a value for the Merchant Transaction ID element.' },
  '8086': { action: 'M', message: 'Your request is missing a value for the Transaction ID element.' },
  '8087': { action: 'M', message: 'You have submitted an invalid accountNum element.' },
  '8088': { action: 'M', message: 'You have submitted a record with an invalid number of fields.' },
  '8090': { action: 'M', message: 'You have submitted an invalid Transaction Date element.' },
  '8091': { action: 'M', message: 'You have submitted an invalid ID Expiration element.' },
  '8092': { action: 'M', message: 'Your have submitted an unsupported transaction type for the Transaction Code element.' },
  '8093': { action: 'M', message: 'You have submitted an invalid billingSchedule element. Your request is either missing a paymentMethodId or missing a new paymentMethod element.' },
  '8094': { action: 'M', message: 'You have submitted an invalid paymentMethod element. Your request is either missing a billingAddressId or missing a new billingAddress element.' },
  '8095': { action: 'M', message: 'You have submitted a file that exceeds the limit of 1000 records.' },
  '8096': { action: 'M', message: 'You have submitted an invalid transactionMode element. Please verify this parameter and retry the transaction.' },
  '8100': { action: 'M', message: 'Your request is missing a value for the aggregateAccountNum element.' },
  '8101': { action: 'M', message: 'You have submitted an invalid aggregateAccountNum element.' },
  '8102': { action: 'M', message: 'You have submitted an invalid Version element.' },
  '8103': { action: 'M', message: 'You have submitted an invalid storeID element.' },
  '8104': { action: 'M', message: 'You have submitted an invalid storePwd element.' },
  '8105': { action: 'M', message: 'You have submitted an accountNum element that is not associated with the aggregateAccountNum element.' },
  '8106': { action: 'M', message: 'You have submitted an invalid aggregateAccountNum element. No aggregated accounts were found.' },
  '8107': { action: 'M', message: 'Your request is missing a value for the intervalValue element.' },
  '8108': { action: 'M', message: 'You have submitted an invalid intervalValue element.' },
  '8109': { action: 'M', message: 'The intervalValue element cannot be provided with the defined intervalCode.' },
  '8110': { action: 'M', message: 'The value for the intervalValue element must be between 1 and 35.' },
  '8112': { action: 'M', message: 'You have submitted an invalid merchantAccount element. The merchant account number provided is not set up for Recurring Billing.' },
  '8119': { action: 'M', message: 'Your request is missing a value for the userName element.' },
  '8120': { action: 'M', message: 'Your request is missing a value for the password element.' },
  '8121': { action: 'M', message: 'Your request is missing a value for the customerIp element.' },
  '8122': { action: 'M', message: 'Your request is missing a value for the siteUrl element.' },
  '8123': { action: 'M', message: 'Your request is missing a value for the keyword element.' },
  '8124': { action: 'M', message: 'Your request is missing a value for the welcomeEmail element.' },
  '8125': { action: 'M', message: 'An internal error occurred. The welcome email could not be generated.' },
  '8127': { action: 'M', message: 'Your request is missing a value for the ddMandateReference child element of the billingSchedule element.' },
  '8128': { action: 'M', message: 'You have submitted an invalid mandate reference. Please verify your parameter and retry the transaction.' },
  '8129': { action: 'M', message: 'You have submitted an invalid financingType element. Please verify your parameter and retry the transaction.' },
  '8130': { action: 'M', message: 'You have submitted an invalid plan element. Please verify your parameter and retry the transaction.' },
  '8131': { action: 'M', message: 'You have submitted an invalid gracePeriod element. Please verify your parameter and retry the transaction.' },
  '8132': { action: 'M', message: 'You have submitted an invalid term element. Please verify your parameter and retry the transaction.' },
  '8133': { action: 'M', message: 'Your request is missing a value for the processingType element.' },
  '8134': { action: 'M', message: 'Your request is missing a value for the appliedDate element.' },
  '8135': { action: 'M', message: 'Your request is missing a value for the echeckId element.' },
  '8136': { action: 'M', message: 'The purchase transaction that corresponds with the recurring billing record you are trying to create could not be located, probably because more than one purchase was processed on the card.' },
  '8136': { action: 'M', message: 'The purchase transaction that corresponds with the recurring billing record you are trying to create could not be located. The consumer and the recurring billing record were created but the welcome email could not be sent.' },
  '8137': { action: 'M', message: 'Your merchant account is not configured for the transaction you attempted.' },
  '8138': { action: 'M', message: 'You submitted an invalid email address with your request.' },
  '8139': { action: 'M', message: 'The routing number length for BACS (Sort Code) should be 6 digits.' },
  '8140': { action: 'M', message: 'The routing number length for ACH should be 9 digits.' },
  '8141': { action: 'M', message: 'The routing number length for EFT (Institution ID/Transit Number) should be 8 digits.' },
  '8142': { action: 'M', message: 'The routing number length for NAB (Bank State Branch) should be 6 digits.' },
  '8143': { action: 'M', message: 'The routing number length for SEPA (BIC) should not exceed 11 characters.' },
  '8144': { action: 'M', message: 'The account number length for BACS should be 8 digits.' },
  '8145': { action: 'M', message: 'The account number length for ACH should not exceed 17 digits.' },
  '8146': { action: 'M', message: 'The account number length for EFT should not exceed 12 digits.' },
  '8147': { action: 'M', message: 'The account number length for NAB (Bank State Branch) should not exceed 9 digits.' },
  '8148': { action: 'M', message: 'The account number length for SEPA (IBAN) should not exceed 34 characters.' },
}
